### PR TITLE
wait for zeo connection (backport from ZEO's pack script)

### PR DESCRIPTION
**Pull request by mamico**
this PR (code backported from ZEO's pack script) try to solve the issue reported here:

https://github.com/zopefoundation/ZEO/issues/99

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
O, can you add a changelog entry for this?

**Comment by mauritsvanrees** [comment]
Can you rebase on master? That should fix the Travis failure.

No need to restart the Jenkins jobs: I see this package is not actually tested on Jenkins.

**Comment by mauritsvanrees** [comment]
O, and for a next time: it is fine to create a branch directly in the current repository in the plone organization, without making a fork. (But there can be reasons for yourself to prefer that, for example if you want to use a checkout in an own project, which is fine.)

**Comment by mamico** [comment]
@mauritsvanrees all done. thanks.

**Pull request merged**
