### PR TITLE
Removing ZODB3_HOME from runzeo.bat and zeoservice.py.in files

### PR DESCRIPTION
**Pull request by fazalsulaiman**

### CODE REVIEW

**Comment by fazalsulaiman** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
We should add Github actions and basic startup tests. Atm my time is limited, but I can answer questions.

**Comment by fazalsulaiman** [comment]
> I guess there was a big renaming from ZODB to ZODB3 a while ago, and these files got changed in the wrong way.
> Looks good to me, but I have not tried it.
> @jensens Do you have a chance to try this?
> 
> There is one failing test on Jenkins, but it is unrelated, so we can ignore that.
> 
> One minor thing: please don't edit the `CHANGES.rst` file directly. Read the comment at the top of that file on what to do instead. In this case, please create a file `news/42.bugfix` and put the changelog entry and your name in there.
> 
> If you can sign the Plone contributor agreement, like mentioned in one of the automated comments, that would help get this (and future PRs) merged.
> But as release manager, I can say that this is an obvious bugfix, and we can gratefully accept it without a signed agreement.

Thanks for the replay, removed  `CHANGES.rst` changes and sent 'Plone Contributor Agreement', waiting for the replay from agreements@plone.org.

**Comment by fazalsulaiman** [comment]
For reopening the request for plone certificate verification

**Comment by jensens** [comment]
@fazalsulaiman next time please do not merge PRs yourself here. In _github.com/plone_ we expect someone else to review and merge the code - after tests are all green. This usually does not take long. 
Opposed to this in _github.com/zopefoundation_ we wait for an positive review and have all tests green - then the submitter should merge the pull request herself/himself.

**Comment by fazalsulaiman** [comment]
> @fazalsulaiman next time please do not merge PRs yourself here. In _github.com/plone_ we expect someone else to review and merge the code - after tests are all green. This usually does not take long.
> Opposed to this in _github.com/zopefoundation_ we wait for an positive review and have all tests green - then the submitter should merge the pull request herself/himself.

Sure, I will do that

**Pull request merged**
