### PR TITLE
Fix for "ValueError: Attempted relative import in non-package" - In windows system

### PR DESCRIPTION
**Pull request by fazalsulaiman**

### CODE REVIEW

**Comment by fazalsulaiman** [comment]
@mauritsvanrees : Please review the change and merge the MR

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by fazalsulaiman** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
I started the Jenkins jobs an hour ago, then you did the same half an hour later, and then a minute later you merged...
If jobs are already running, and there are no new changes, then please wait will the jobs are finished. This *should* be clear in the status checks, but it may take some getting used to.
And starting new jobs and then immediately merging, is not very useful.

Anyway, I checked the jobs that I started and they were all green, so it's okay. But in my part of the world it is hot enough already: we don't need extra heat generated by a server running those jobs. ;-)

But thanks for working on Windows issues! Great to have more people who care about that!

**Comment by jugmac00** [comment]
@mauritsvanrees While the plone contributing process is much more streamlined than most others I know, isn't it possible to restrict merging to successfully tested branches?

This would take away some burden from new contributors to go through a pretty long mental checklist.

**Comment by jensens** [comment]
Sure, this is possible, but we need to add the protected branches for every single repository in Plone, that's quite annoying. I added master branch protection for this repository now.

**Comment by jugmac00** [comment]
This should be possible via API, but at 35 ° C it is preferable to go to beach and keep the status quo 😉

**Comment by fazalsulaiman** [comment]
> I started the Jenkins jobs an hour ago, then you did the same half an hour later, and then a minute later you merged...
> If jobs are already running, and there are no new changes, then please wait will the jobs are finished. This _should_ be clear in the status checks, but it may take some getting used to.
> And starting new jobs and then immediately merging, is not very useful.
> 
> Anyway, I checked the jobs that I started and they were all green, so it's okay. But in my part of the world it is hot enough already: we don't need extra heat generated by a server running those jobs. ;-)
> 
> But thanks for working on Windows issues! Great to have more people who care about that!

Thank you @mauritsvanrees for the details and I will follow that

**Pull request merged**
