### PR TITLE
Add support for log rotation

### LINKED ISSUE #17: Add support for event log rotation
Currently the ZEO server event log grows without limit and that's far from optimal.

We can take ideas from [plone.recipe.zope2instance](https://github.com/plone/plone.recipe.zope2instance/search?utf8=%E2%9C%93&q=event-log-max-size) on how to implement that.

### PR DESCRIPTION
**Pull request by hvelarde**
This is based on the same feature found in [plone.recipe.zope2instance](https://github.com/plone/plone.recipe.zope2instance).

closes #17

### CODE REVIEW

**Comment by hvelarde** [comment]
guys, I'm asking you to review as you were the latest contributors to this package.

**Comment by hvelarde** [comment]
@ale-rt I copied the text that is on the other recipe; besides that, do you know were the parsing magic occurs? I'm curious because I want to implement a similar feature for [collective.fingerpointing](https://github.com/collective/collective.fingerpointing).

I'm merging regardless the error in Plone 4.3 as is not related with this package; BTW, I think tests are not running anywhere in Jenkins; this recipe should be tested in Travis.

thanks!

**Comment by mauritsvanrees** [comment]
Error on Jenkins 4.3, but that is due to an unrelated change that I made in coredev and have now undone (Zope2 needs to be checked out). I will restart the pull request job.

**Comment by hvelarde** [comment]
@mauritsvanrees are you sure tests of this package are run in Jenkins? I don't see any evidence on the log.

**Comment by hvelarde** [comment]
done! a new release should be highly appreciated.

**Comment by ale-rt** [comment]
@hvelarde what do you mean by "parsing magic"?
The doc test is initialized here:

- https://github.com/plone/plone.recipe.zeoserver/blob/master/src/plone/recipe/zeoserver/tests/test_docs.py#L45

**Comment by mauritsvanrees** [comment]
I have released plone.recipe.zeoserver 1.3 with this feature. Thanks!

**Comment by hvelarde** [comment]
@ale-rt I menat, do you know where Zope parses the size in configuration including suffixes (KB, MB, GB)?

**Pull request merged**
